### ISSUE TITLE
Makefile missing?

### ISSUE THREAD

**Issue by Norgg** [xbpeng/DeepTerrainRL#1]
I'm not sure if it's intentional or not, but /Makefile is in .gitignore and I don't see any other means to build it except a visual studio project, which is strange since there's only Linux instructions in the readme.

Is a Makefile intended to be distributed with this?

**Comment by xbpeng** [comment]
The makefile was being generated by premake, but we don't have that setup yet for this version of the code. It's on our todo list, and will let you know when that is ready.

**Comment by Norgg** [comment]
Great, thanks! Really cool work by the way.

**Comment by zdx3578** [comment]
To simulate a controller/character
./TerrainRL -arg_file= args/sim_dog_args.txt
To simulate a controller/character with a specific policy
./TerrainRL_Optimizer -arg_file= 

TerrainRL TerrainRL_Optimizer also in  .gitignore ; later this two file will can be build?

**Comment by xbpeng** [comment]
yes, TerrainRL and TerrainRL_Optimizer are built by separate projects. We are still working to get a new makefile setup. But in the meantime, the visual studio projects should work.

**Comment by zdx3578** [comment]
Great work！

**Comment by Neo-X** [comment]
Hello,

I have pushed the premake file I used to build the project. Everything seems to build fine. I attach my external folder (contains most third party libraries) to a release that was just published. You will need that to compile the code on Linux.
