### ISSUE TITLE
Where  library.zip file for Windows build?

### ISSUE THREAD

**Issue by maximale** [xbpeng/DeepTerrainRL#12]
Where  download library.zip file for Windows build?

**Comment by Neo-X** [comment]
Hmmm, I can upload the library.zip file I use but I think the version of caffe is going to be incorrect for this code.

**Comment by Neo-X** [comment]
I Have uploaded it here
https://github.com/xbpeng/DeepTerrainRL/releases/download/v1.1.1/library.zip
