### ISSUE TITLE
Where is dynamic_lib.zip for Windows?

### ISSUE THREAD

**Issue by smkang96** [xbpeng/DeepTerrainRL#14]
The Windows solution references a dynamic_lib.zip, but I couldn't find it in the releases.

**Comment by Neo-X** [comment]
Where do you see a reference to this? I think it might be inside the library.zip file.

**Comment by smkang96** [comment]
In the Windows build instructions, the fourth step says:
You will need to copy some dll files from **dynamic_lib.zip** to the directory the project is compiled to. For example, optimizer/x64/Debug/. These files are needed by the framework during runtime.

**Comment by Neo-X** [comment]
Yes, this should be in the library.zip file attached to one of the release.
