### ISSUE TITLE
Compiling successfully but only one executable? 

### ISSUE THREAD

**Issue by shihuiguo** [xbpeng/DeepTerrainRL#18]
I think I followed all the steps and there is no error message (except for warning about the unused variables and comparison between signed/unsigned expression).

But after the compilation, I only found one executable: TerrainRL, but didn't find another one: TerrainRL_Optimize. But when I run the TerrainRL, the window pops up, the framerate number is flashing, but I saw nothing except a blank window.

Did I miss anything?

**Comment by Neo-X** [comment]
To compile the second executable you need to open the solution for TerrainRL_Optimizer in the optimizer directory.

For the second issue please see the notes on how to run the system [here](https://github.com/xbpeng/DeepTerrainRL#runing-the-system). I don't think you are specifying an arg_file to the program.

**Comment by shihuiguo** [comment]
Yep, great, it seems to be working.

I must have some typo yesterday to run the executable. Today I just copy the command, it works.

To compile the optimizer, for anyone who possibly meets the same problem

cd optimizer/
make config=debug64 -j8

if you are using the release version (linux, in May 2016), you need to remove DMACETrainer - Copy.cpp/DMACETrainer - Copy.h, and edit the Makefile correspondingly. Just check out the newest version should be a safe solution.

Thank you again @Neo-X , and to @xbpeng to make this open source
