### ISSUE TITLE
Performance Issue (only using one CPU core?)

### ISSUE THREAD

**Issue by shihuiguo** [xbpeng/DeepTerrainRL#19]
After successfully running the demo, I found that TerrainRL is only using one CPU core on my PC (Ubuntu 14.04) and the framerate is 5fps. My PC is 4 CPU cores and 8G memory.

Did I miss any detail? Or this is normal? Thanks for all.

Shihui

**Comment by xbpeng** [comment]
The TerrainRL app is single threaded, the optimizer is multithreaded. Are you building in Debug or Release? Release should run in realtime.

**Comment by shihuiguo** [comment]
Yes, it works perfectly, the release version works in real time.

Thanks, =)
