### ISSUE TITLE
unique_ptr for mNet,  and shared_ptr for mSolver?

### ISSUE THREAD

**Issue by shihuiguo** [xbpeng/DeepTerrainRL#21]
Is there any specific reason for adopting the usage of unique_ptr and shared_ptr? Is it related to the data synchronisation during the parallel computing?

Thanks.

Shihui

**Comment by xbpeng** [comment]
It was mainly to help prevent memory leaks.

**Comment by shihuiguo** [comment]
Thanks Peng.

But is this approach mandatory or recommended? I am wondering whether I should adopt the same mechanism in my code, =)

Shihui

**Comment by xbpeng** [comment]
I think it's safer than using raw pointers.
