### ISSUE TITLE
==== Building TerrainRL (debug32) ==== CaclaTrainer.cpp

### ISSUE THREAD

**Issue by aysegulucar2016** [xbpeng/DeepTerrainRL#22]
do you have clear correct instruction steps?
I applied below steps:

# 1
git clone https://github.com/xbpeng/DeepTerrainRL.git
cd DeepTerrainRL/
# 2
wget https://github.com/xbpeng/DeepTerrainRL/releases/download/v1.0/TerrainRL-external-Linux.tar.gz
tar zxvf TerrainRL-external-Linux.tar.gz 
# 3
wget https://github.com/xbpeng/DeepTerrainRL/files/517743/terrainnRL_premake4.zip 
unzip terrainnRL_premake4.zip 
# 4
cp ~/DeepTerrainRL/caffe_mods/caffe.proto ~/DeepTerrainRL/external/caffe/src/caffe/proto/caffe.proto
cp ~/DeepTerrainRL/caffe_mods/memory_data_layer.cpp ~/DeepTerrainRL/external/caffe/src/caffe/layers/memory_data_layer.cpp
cp ~/DeepTerrainRL/caffe_mods/memory_data_layer.hpp ~/DeepTerrainRL/external/caffe/include/caffe/layers/memory_data_layer.hpp 
# 5
premake4 gmake
# 6
make

I received error after make
==== Building TerrainRL (debug32) ====
CaclaTrainer.cpp
In file included from /usr/include/c++/5/memory:62:0,
                 from ./learning/NeuralNetTrainer.h:2,
                 from ./learning/ACTrainer.h:3,
                 from learning/CaclaTrainer.h:3,
                 from learning/CaclaTrainer.cpp:1:
/usr/include/c++/5/bits/stl_algobase.h:59:28: fatal error: bits/c++config.h: No such file or directory
compilation terminated.
TerrainRL.make:275: recipe for target 'obj/x32/Debug/CaclaTrainer.o' failed
make[1]: *** [obj/x32/Debug/CaclaTrainer.o] Error 1
Makefile:16: recipe for target 'TerrainRL' failed
make: *** [TerrainRL] Error 2
-----------------------------------------------------------

**Comment by Neo-X** [comment]
You need to install the bits libraries. Make sure to install all of the dependencies first. In this case
sudo apt-get install gcc-4.9-multilib g++-4.9-multilib

**Comment by aysegulucar2016** [comment]
I did it  
it presents same error.
