### ISSUE TITLE
==== Building TerrainRL (debug32) ==== CaclaTrainer.cpp In file included from /usr/include/c++/5/memory:62:0,

### ISSUE THREAD

**Issue by aysegulucar2016** [xbpeng/DeepTerrainRL#23]
sudo apt-get install gcc-4.9-multilib g++-4.9-multilib

I didt it
/DeepTerrainRL$ make config=debug64
==== Building TerrainRL (debug64) ====
CaclaTrainer.cpp
In file included from external/caffe/include/caffe/blob.hpp:9:0,
                 from external/caffe/include/caffe/net.hpp:10,
                 from ./learning/NeuralNet.h:3,
                 from ./learning/TrainerInterface.h:3,
                 from ./learning/NeuralNetTrainer.h:4,
                 from ./learning/ACTrainer.h:3,
                 from learning/CaclaTrainer.h:3,
                 from learning/CaclaTrainer.cpp:1:
external/caffe/build/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
external/caffe/build/src/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
external/caffe/build/src/caffe/proto/caffe.pb.h:14:2: error: #error your headers.

**Comment by Neo-X** [comment]
See #24.
