### ISSUE TITLE
~/DeepTerrainRL/external/caffe$ make error

### ISSUE THREAD

**Issue by aysegulucar2016** [xbpeng/DeepTerrainRL#24]
Could you please answer? what is problem?
~/DeepTerrainRL/external/caffe$ make
find: ‘tools’: No such file or directory
find: ‘examples’: No such file or directory
find: ‘matlab/+caffe/private’: No such file or directory
find: ‘examples’: No such file or directory
find: ‘tools’: No such file or directory
find: ‘matlab/’: No such file or directory
find: ‘examples’: No such file or directory
find: ‘tools’: No such file or directory
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:0:
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
.build_release/src/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
.build_release/src/caffe/proto/caffe.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:0:

**Comment by Neo-X** [comment]
The problem is 
```
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
```
You should regenerate the proto files in caffe.
