### ISSUE TITLE
 Why does external folder include two caffe folders, caffe and caffe-master. Which one should I use?

### ISSUE THREAD

**Issue by aysegulucar2016** [xbpeng/DeepTerrainRL#25]
Why does external folder include two caffe folders, caffe and caffe-master.

Which one should I use?
~/DeepTerrainRL/external/caffe-master$ make
or

~/DeepTerrainRL/external/caffe$ make

**Comment by Neo-X** [comment]
You should use DeepTerrainRL/external/caffe.
