### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [xbpeng/DeepTerrainRL#3]
[An extra null pointer check is not needed](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8) in [the function "cWorld::tConstraintHandle::Clear"](https://github.com/xbpeng/DeepTerrainRL/blob/9bd6688598fe82d1e7189b9256693868bb9d4cdd/sim/World.cpp#L43).

**Comment by xbpeng** [comment]
got it, thanks for pointing that out. Will fix.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/xbpeng/DeepTerrainRL/commit/491b9cca249fdf420448b1489705574f7ec5b101#diff-e74b8c7068397902899fd8143cd73d54L43).
