### ISSUE TITLE
Segmentation Fault when running TerrainRL

### ISSUE THREAD

**Issue by MiaoDragon** [xbpeng/DeepTerrainRL#37]
Hello. I'm testing this project on my Mac OSX. However, when I run the command "./TerrainRL -arg_file= args/sim_dog_args.txt", it got a segmentation fault. The following is the log:

"
*** Aborted at 1505824491 (unix time) try "date -d @1505824491" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 666 (TID 0x7fff7de7e000) stack trace: ***
    @     0x7fff9788152a _sigtramp
    @        0x10bc33d91 gBKGColor
    @        0x10b9246c7 cTextureDesc::cTextureDesc()
    @        0x10b92472c cTextureDesc::cTextureDesc()
    @        0x10bb8b32b InitOpenGl()
    @        0x10bb8b5d3 main
    @     0x7fff988895ad start
Segmentation fault: 11
"

My computer has 16G memory, and I didn't change the code, except premake and makefile to make it work on my machine. I also tested that TerrainRL_Optimizer works fine. Could you help me with this issue? Thanks in advance!

**Comment by xbpeng** [comment]
It looks like an issue with OpenGL.

**Comment by MiaoDragon** [comment]
Thanks! It is due to the "ifdef LINUX" in render/TextureUtil.cpp. I guess Mac uses the same method as Linux.
