### ISSUE TITLE
build with caffe in library.zip failed

### ISSUE THREAD

**Issue by MiaoDragon** [xbpeng/DeepTerrainRL#39]
Hi! I'm building this project on my Mac OS X system. I downloaded "library.zip" file and got the caffe built successfully. However, when I make the project, some linking issues occurred:

"
==== Building TerrainRL (debug64) ====
Linking TerrainRL
Undefined symbols for architecture x86_64:
  "caffe::Net<double>::Net(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::Phase, caffe::Net<double> const*)", referenced from:
      cNeuralNet::cCaffeNetWrapper::cCaffeNetWrapper(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::Phase) in NeuralNet.o
  "caffe::Solver<double>::Solver(caffe::SolverParameter const&, caffe::Solver<double> const*)", referenced from:
      caffe::SGDSolver<double>::SGDSolver(caffe::SolverParameter const&) in NNSolver.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [TerrainRL] Error 1
make: *** [TerrainRL] Error 2
"

However, in the makefile, I have correctly set the path. To add: the "make test" of caffe also failed because of linking issues like this.
Could you help me with this problem?

**Comment by xbpeng** [comment]
it looks like it's having trouble finding the definition for caffe::Phase. Maybe take a look at the caffe source and see if it is properly defined somewhere?
