### ISSUE TITLE
build iLQR control method for this problem

### ISSUE THREAD

**Issue by MiaoDragon** [xbpeng/DeepTerrainRL#40]
Hi! After seeing the impressive power of iLQR (Iterative Linear Quadratic Regulator), I'd like to apply this method to this problem and see if it works well. I'd like to first try to use this to control the same actions of the RL method, i.e., the FSM parameters. I may also consider directly controlling torques as a future work.

However, I'm really new to this and don't know what to start first. Could you give me some advice on the files that I may look at, such as the FSM parameters and controllers, and the files in the project which may be related to my implementation? I guess the actions are acting as a reference state or forces to the FSM phases, but don't know if I'm correct. Could you please explain more about their relation?

Thank you in advance for the help!

**Comment by Neo-X** [comment]
A good place to start would be reading  Rich Suttons book on Reinforcement Learning.

**Comment by MiaoDragon** [comment]
Thank you for the response! I will look at this book.
