### ISSUE TITLE
Simulation speed

### ISSUE THREAD

**Issue by nyp0x** [xbpeng/DeepTerrainRL#44]
Just builded TerrainRL in Debug x64 mode (win10, vs2013) and launched it with _sim_dog_args.txt_ arguments. It gives only 1.9 fps on the average on 4-core i7-6700 CPU (3.4 GHz). Weirdly enough, the process takes only 18% of the CPU load. It this performance expected? Or maybe something is wrong with the libraries. However, only CUDA version (8.0) is different from the original dependency list.
Also wanted to try new DeepMimic approach, but didn't find the code. How much time it takes to simulate an animation frame of that awesome Ziva Dynamics lion?
Thanks!

**Comment by xbpeng** [comment]
debug tends to be very slow, try building in release. When running the optimizer, you can specify the number of threads with the -num_threads= argument.
