### ISSUE TITLE
how can i solve compile error?

### ISSUE THREAD

**Issue by dreamexe** [xbpeng/DeepTerrainRL#5]
1>learning\NeuralNet.cpp(484): error C2039: 'AddData' : is not a member of 'caffe::MemoryDataLayercNeuralNet::tNNData'
1>learning\NeuralNet.cpp(1126): error C2039: 'AddData' : is not a member of 'caffe::MemoryDataLayercNeuralNet::tNNData'

build on   vs2013 . win10  can you help me?

**Comment by xbpeng** [comment]
We've made some changes to caffe. You can find the modified files in caffe_mods/. Merge the changes in those files with the original ones in caffe, then rebuild caffe.pb.cc and caffe.pb.h. That should fix those errors.

**Comment by dreamexe** [comment]
thanks :) 
would ask one more request ?
there is no shader file on Git rep.
can you upload please?

**Comment by dreamexe** [comment]
thanks :)
